# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InterviewTestDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 5.0.1'
pod 'SwiftyJSON'
  # Pods for InterviewTestDemo

  target 'InterviewTestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InterviewTestDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
